---
- hosts: localhost
  vars:
    - username: "{{ USER }}"
    - home: "{{ GROUP }}"
  tasks:
    - name: print variables values
      debug:
        msg: "Username: {{ username }}, Home dir: {{ home }}"
